language: ruby

before_install:
  - gem install bundler

rvm:
  - 2.4.1

gemfile:
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-edge.gemfile

addons:
  chrome: stable
