language: ruby

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.6.0

gemfile:
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-edge.gemfile

addons:
  chrome: stable

matrix:
  exclude:
    gemfile: gemfiles/rails-4.2.gemfile

  include:
    gemfile: gemfiles/rails-4.2.gemfile
    before_install:
      - gem install bundler -v '< 2'
