os: linux
dist: bionic

language: ruby

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.6.10
  - 2.7.6

gemfile:
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-6.0.gemfile
  - gemfiles/rails-6.1.gemfile

addons:
  chrome: stable

jobs:
  include:
    - gemfile: gemfiles/rails-4.2.gemfile
      before_install:
        - gem install bundler -v '< 2'

    - gemfile: gemfiles/rails-6.1.gemfile
      rvm: 3.0.4

    - gemfile: gemfiles/rails-7.0.gemfile
      rvm: 2.7.6

    - gemfile: gemfiles/rails-7.0.gemfile
      rvm: 3.0.4
